"""Add activities details

Revision ID: 72c74b0feaea
Revises: 44b9c1dddab6
Create Date: 2026-08-15 22:23:45.513759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c74b0feaea'
down_revision: Union[str, Sequence[str], None] = '44b9c1dddab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'details')
    # ### end Alembic commands ###
